# Generated by Django 4.2 on 2023-05-09 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=15)),
                ('yosh', models.SmallIntegerField()),
                ('kurs', models.SmallIntegerField()),
                ('student_raqam', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=20)),
                ('sana', models.DateField(auto_now_add=True)),
                ('batafsil', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.student')),
            ],
        ),
    ]
