# Generated by Django 4.2 on 2023-05-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reja',
            name='student',
        ),
        migrations.AddField(
            model_name='reja',
            name='yonalish',
            field=models.CharField(blank=True, choices=[('Hozirgi maqsad', 'Hozirgi maqsad'), ('Kelajakdagi maqsad', 'Kelajakdagi maqsad')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
